version: "3.7"
services:
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:amd64-latest
    volumes:
      - /srv/sonarr/config:/config
      - /media:/media
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${SONARR_HOST}
      - LETSENCRYPT_HOST=${SONARR_HOST}
      - VIRTUAL_PORT=8989
      - DOCKER_MODS=gilbn/theme.park:sonarr

  radarr:
    container_name: radarr
    image: linuxserver/radarr:amd64-latest
    volumes:
      - /srv/radarr/config:/config
      - /media:/media
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${RADARR_HOST}
      - LETSENCRYPT_HOST=${RADARR_HOST}
      - VIRTUAL_PORT=7878
      - DOCKER_MODS=gilbn/theme.park:radarr

  bazarr:
    container_name: bazarr
    image: linuxserver/bazarr:amd64-latest
    volumes:
      - /srv/bazarr/config:/config
      - /media:/media
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${BAZARR_HOST}
      - LETSENCRYPT_HOST=${BAZARR_HOST}
      - VIRTUAL_PORT=6767
      - DOCKER_MODS=gilbn/theme.park:bazarr

  emby:
    container_name: emby
    image: emby/embyserver:latest
    volumes:
      - /srv/emby/config:/config
      - /media:/media
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${EMBY_HOST}
      - LETSENCRYPT_HOST=${EMBY_HOST}
      - VIRTUAL_PORT=8096

  jackett:
    container_name: jackett
    image: linuxserver/jackett:amd64-latest
    volumes:
      - /srv/jackett/config:/config
      - /srv/transmission/watch:/downloads
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${JACKETT_HOST}
      - LETSENCRYPT_HOST=${JACKETT_HOST}
      - VIRTUAL_PORT=9117
      - DOCKER_MODS=gilbn/theme.park:jackett

  transmission:
    image: linuxserver/transmission:amd64-latest
    container_name: transmission
    volumes:
      - /srv/transmission/config:/config
      - /srv/transmission/watch:/watch
      - /media/downloads:/downloads
    ports:
      - 51413:51413
      - 51413:51413/udp
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${TRANSMISSION_HOST}
      - LETSENCRYPT_HOST=${TRANSMISSION_HOST}
      - VIRTUAL_PORT=9091
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
      - DOCKER_MODS=gilbn/theme.park:transmission
      - TRANSMISSION_WEB_HOME=/combustion-release/

  netdata:
    container_name: netdata
    image: netdata/netdata:latest
    hostname: ubuntu.dlink
    cap_add:
      - SYS_PTRACE
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/netdata/etc/netdata:/etc/netdata
      - /srv/netdata/var/lib/netdata:/var/lib/netdata
      - /srv/netdata/var/cache/netdata:/var/cache/netdata
    security_opt:
      - apparmor:unconfined
    restart: always
    environment:
      - VIRTUAL_HOST=${NETDATA_HOST}
      - VIRTUAL_PORT=199999
      - PGID=998

  agent:
    container_name: portainer_agent
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

  portainer:
    container_name: portainer_server
    image: portainer/portainer-ce
    command: -H tcp://agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    environment:
      - VIRTUAL_HOST=${PORTAINER_HOST}
      - VIRTUAL_PORT=9000

  duplicati:
    container_name: duplicati
    image: linuxserver/duplicati:amd64-latest
    volumes:
      - /srv/duplicati/config:/config
      - /srv:/backups
      - /srv/duplicati/source:/source
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - VIRTUAL_HOST=${DUPLICATI_HOST}
      - VIRTUAL_PORT=8200

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    environment:
      - TZ=Europe/Warsaw
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 5 * * *
      - WATCHTOWER_NOTIFICATIONS=slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${WATCHTOWER_HOOK_URL}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=warn
      - WATCHTOWER_NO_STARTUP_MESSAGE=true

  bitwarden-rs:
    container_name: bitwarden-rs
    image: bitwardenrs/server:latest
    volumes:
      - /srv/bitwarden/:/data/
    restart: always
    environment:
      - PUID=911
      - UID=911
      - GID=911
      - TZ=Europe/Warsaw
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=false
      - VIRTUAL_HOST=${BITWARDEN_HOST}
      - LETSENCRYPT_HOST=${BITWARDEN_HOST}

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:latest
    volumes:
      - /srv/nginx/conf.d:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - /srv/nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    environment:
      - TZ=Europe/Warsaw
    ports:
      - 80:80
      - 443:443

  nginx-proxy-letsencrypt:
    container_name: nginx-proxy-letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - certs:/etc/nginx/certs
      - /srv/nginx/vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - TZ=Europe/Warsaw

volumes:
  certs:
  html:
  portainer_data:
